const CARDS = [
    // 騎士 (Knight)
    {
        id: 'kn_icon_guardian',
        name: '辺境守護騎士',
        faction: 'knight',
        type: 'icon',
        cost: 1,
        clock: -1,
        influence: 1,
        copies: 4,
        image: 'images/kn_icon_guardian.png',
        style: '銅版画風',
        effect: '破壊される際、代わりに手札1枚を消費して場に留まることができる。'
    },
    {
        id: 'kn_icon_commander',
        name: '前線指揮官',
        faction: 'knight',
        type: 'icon',
        cost: 2,
        clock: -1,
        influence: 2,
        copies: 2,
        image: 'images/kn_icon_commander.png',
        style: '銅版画風',
        effect: '場に出た時、手札1枚を破棄(消費)できる。そうした場合、即座に基本コスト0で強奪を行う。'
    },
    {
        id: 'kn_fab_raid',
        name: '鉄槌の急襲',
        faction: 'knight',
        type: 'fabula',
        cost: 1,
        clock: -1,
        influence: 0,
        copies: 2,
        image: 'images/kn_fab_raid.png',
        style: '銅版画風',
        effect: '相手のイコン1体を破壊する。それがマクガフィンを保持していたなら、破壊後に強奪する。'
    },
    {
        id: 'kn_fab_march',
        name: '焦土の進軍',
        faction: 'knight',
        type: 'fabula',
        cost: 2,
        clock: -1,
        influence: 0,
        copies: 2,
        image: 'images/kn_fab_march.png',
        style: '銅版画風',
        effect: '山札から2枚引く。このターン、自分の騎士イコンの「強奪」基本コストは0になる。'
    },
    // 聖職者 (Clergy)
    {
        id: 'cl_icon_bishop',
        name: '鎮魂の司教',
        faction: 'clergy',
        type: 'icon',
        cost: 1,
        clock: 1,
        influence: 1,
        copies: 4,
        image: 'images/cl_icon_bishop.png',
        style: 'ステンドグラス風',
        effect: 'このカードは相手のファブラの効果の対象にならない。'
    },
    {
        id: 'cl_icon_saint',
        name: '終焉を嘆く聖女',
        faction: 'clergy',
        type: 'icon',
        cost: 2,
        clock: 1,
        influence: 1,
        copies: 2,
        image: 'images/cl_icon_saint.png',
        style: 'ステンドグラス風',
        effect: 'このカードが場にある限り、全プレイヤーは「破棄」を伴うアクションを行えない。'
    },
    {
        id: 'cl_fab_miracle',
        name: '奇跡の顕現',
        faction: 'clergy',
        type: 'fabula',
        cost: 1,
        clock: 1,
        influence: 0,
        copies: 2,
        image: 'images/cl_fab_miracle.png',
        style: 'ステンドグラス風',
        effect: '捨て札からイコン1体をコストなしで場に出す。その後、そこへマクガフィンを移動させてよい。'
    },
    {
        id: 'cl_fab_prayer',
        name: '静寂の祈り',
        faction: 'clergy',
        type: 'fabula',
        cost: 2,
        clock: 1,
        influence: 0,
        copies: 2,
        image: 'images/cl_fab_prayer.png',
        style: 'ステンドグラス風',
        effect: '次の自分のターン開始時まで、自分の場のイコンすべては効果によって破壊されない。'
    },
    // 貴族 (Noble)
    {
        id: 'ar_icon_duke',
        name: '沈黙の公爵',
        faction: 'noble',
        type: 'icon',
        cost: 2,
        clock: 0,
        influence: 2,
        copies: 3,
        image: 'images/ar_icon_duke.png',
        style: 'ゴシック油彩',
        effect: '相手がこのカードから強奪を行う際、追加で手札2枚を消費させる（払えなければ失敗）。'
    },
    {
        id: 'ar_icon_queen',
        name: '盤上を統べる女王',
        faction: 'noble',
        type: 'icon',
        cost: 3,
        clock: 0,
        influence: 3,
        copies: 1,
        image: 'images/ar_icon_queen.png',
        style: 'ゴシック油彩',
        effect: '自分のターン開始時、手札1枚を破棄できる。そうした場合、次の自分のターン開始時まで相手は「強奪」を行えない。'
    },
    {
        id: 'ar_fab_edict',
        name: '無慈悲な勅令',
        faction: 'noble',
        type: 'fabula',
        cost: 2,
        clock: 0,
        influence: 0,
        copies: 2,
        image: 'images/ar_fab_edict.png',
        style: 'ゴシック油彩',
        effect: '相手1人は手札2枚を消費する。できない場合、その場のイコン1体を破壊する。'
    },
    {
        id: 'ar_fab_execute',
        name: '王権の強制執行',
        faction: 'noble',
        type: 'fabula',
        cost: 3,
        clock: 0,
        influence: 0,
        copies: 2,
        image: 'images/ar_fab_execute.png',
        style: 'ゴシック油彩',
        effect: '相手のイコンが保持するマクガフィンを奪う。相手の能力（耐性やコスト増など）をすべて無視する。'
    },
    // 民衆 (People)
    {
        id: 'pe_icon_rebel',
        name: '路地裏の反抗者',
        faction: 'people',
        type: 'icon',
        cost: 0,
        clock: 0,
        influence: 1,
        copies: 8,
        image: 'images/pe_icon_rebel.png',
        style: '木版画風',
        effect: '自分の場に他の民衆イコンがあるなら、因果律は+1される。'
    },
    {
        id: 'pe_icon_patriot',
        name: '名もなき革命家',
        faction: 'people',
        type: 'icon',
        cost: 1,
        clock: 0,
        influence: 1,
        copies: 6,
        image: 'images/pe_icon_patriot.png',
        style: '木版画風',
        effect: '自分のターン中、自分の場の民衆イコン1枚につき、相手イコンの能力1つを選んで無効化する。'
    },
    {
        id: 'pe_fab_network',
        name: '地下の連絡網',
        faction: 'people',
        type: 'fabula',
        cost: 1,
        clock: 0,
        influence: 0,
        copies: 5,
        image: 'images/pe_fab_network.png',
        style: '木版画風',
        effect: '場の民衆の数+1枚、カードをドローする。'
    },
    {
        id: 'pe_fab_riot',
        name: '暴動の火蓋',
        faction: 'people',
        type: 'fabula',
        cost: 1,
        clock: 0,
        influence: 0,
        copies: 5,
        image: 'images/pe_fab_riot.png',
        style: '木版画風',
        effect: '相手イコン1体をランダムに手札に戻す。そのプレイコストが「2以上」なら、戻さず破壊する。'
    }
];
